package tablas;
// Generated 28-ene-2015 15:41:03 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Componente generated by hbm2java
 */
public class Componente  implements java.io.Serializable {


     private Integer cod;
     private Subtipo subtipo;
     private String nombre;
     private Double precioP;
     private Double precioC;
     private Integer stock;
     private String descripcion;
     private Date fechaCompra;
     private Boolean estado;
     private String foto;

    public Componente() {
    }

    public Componente(Subtipo subtipo, String nombre, Double precioP, Double precioC, Integer stock, String descripcion, Date fechaCompra, Boolean estado, String foto) {
       this.subtipo = subtipo;
       this.nombre = nombre;
       this.precioP = precioP;
       this.precioC = precioC;
       this.stock = stock;
       this.descripcion = descripcion;
       this.fechaCompra = fechaCompra;
       this.estado = estado;
       this.foto = foto;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public Subtipo getSubtipo() {
        return this.subtipo;
    }
    
    public void setSubtipo(Subtipo subtipo) {
        this.subtipo = subtipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getPrecioP() {
        return this.precioP;
    }
    
    public void setPrecioP(Double precioP) {
        this.precioP = precioP;
    }
    public Double getPrecioC() {
        return this.precioC;
    }
    
    public void setPrecioC(Double precioC) {
        this.precioC = precioC;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


