package tablas;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

// Generated 28-ene-2015 15:41:03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Subtipo generated by hbm2java
 */
public class Subtipo implements java.io.Serializable {

	private Integer cod;
	private Tipo tipo;
	private String nombre;
	private Set<Componente> componentes = new HashSet<Componente>(0);

	public Subtipo() {
	}

	public Subtipo(Tipo tipo, String nombre, Set<Componente> componentes) {
		this.tipo = tipo;
		this.nombre = nombre;
		this.componentes = componentes;
	}

	public Integer getCod() {
		return this.cod;
	}

	public void setCod(Integer cod) {
		this.cod = cod;
	}

	public Tipo getTipo() {
		return this.tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Cascade({CascadeType.ALL})
	public Set<Componente> getComponentes() {
		return this.componentes;
	}

	public void setComponentes(Set<Componente> componentes) {
		this.componentes = componentes;
	}

}
