package tablas;

// Generated 28-ene-2015 15:41:03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo implements java.io.Serializable {

	private Integer cod;
	private String nombre;
	private Set<Subtipo> subtipos = new HashSet<Subtipo>(0);

	public Tipo() {
	}

	public Tipo(String nombre, Set<Subtipo> subtipos) {
		this.nombre = nombre;
		this.subtipos = subtipos;
	}

	public Integer getCod() {
		return this.cod;
	}

	public void setCod(Integer cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Subtipo> getSubtipos() {
		return this.subtipos;
	}

	public void setSubtipos(Set<Subtipo> subtipos) {
		this.subtipos = subtipos;
	}

}
